#-*- coding: utf-8 -*-

{
	"name": "SH Physical Server",
	"version": "1.0", 
	"depends": [
		'base'
	],
	"author": "Alex Grisales Rivera",
	"category": "Utility",
	"website": "",
	
	"price": "10",
	"license": "OPL-1",
	"currency": "USD",
	"summary": "This is the Physical Server module generated by StarUML Odoo Generator Pro Version",
	"description": """

Information
======================================================================

* created menus
* created objects
* created views
* logics

""",
	"data": [
		"security/ir.model.access.csv",
		"view/menu.xml",
        "view/sh_cloud_provider.xml",
		"view/sh_physical_server.xml",
	],
    'assets': {
                'web.assets_backend': [
                                            'sh_physical_server/static/css/backend.css',
                                        ],
                },
	"installable": True,
	"auto_install": False,
	"application": True,
}